### ISSUE TITLE
Generating simulated perfect reads

### ISSUE THREAD

**Issue by Hendricks27** [yukiteruono/pbsim3#32]
To whom it may concern,

Thank you for developing and maintaining the fantastic pbsim series! I have a quick question: if I set the accuracy-mean parameter to 1, is it guaranteed that the simulated reads will map back to the FASTA file with no errors? Additionally, do the error model and QS model treat accuracy-mean differently?

If the generated reads are not a perfect match, is there an alternative method to achieve that?

Thank you!

**Comment by yukiteruono** [comment]
Thank you for using PBSIM3.
PBSIM is designed to generate error-prone reads, and due to the design constraints, it cannot generate "error-free" reads even if you specify the option --accuracy-mean 1.
By using the option --perfect, [NanoSim](https://github.com/bcgsc/NanoSim) can generate error-free "perfect" reads.

**Comment by Hendricks27** [comment]
Thank you for your prompt response!
I understand now. Setting --accuracy-mean to 1 would result in nearly perfect, but not entirely error-free, reads. is that correct? Thanks again!

**Comment by Hendricks27** [comment]
For interested people, I tried the QS model with accuracy set to 1. The final accuracy reported is around 96%.
